name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Install dependencies
      run: dotnet restore portfolio.csproj

    - name: Build
      run: dotnet build portfolio.csproj --configuration Release --no-restore

    - name: Publish .NET Project
      run: dotnet publish portfolio.csproj -c Release -o release --no-restore

    - name: Copy wwwroot contents
      run: |
        cp -r release/wwwroot/* release/
        rm -rf release/wwwroot

    - name: Add .nojekyll file
      run: touch release/.nojekyll

    # Add CNAME file for custom domain
    - name: Create CNAME file
      run: echo "topedaramola.com" > release/CNAME

    - name: Fix base href
      run: |
        sed -i 's|<base href="/" />|<base href="/topedaramola-2025/" />|g' release/index.html
        echo "Checking updated index.html:"
        cat release/index.html | grep -i "base href"

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4.5.0
      with:
        folder: release
        branch: gh-pages
        clean: true