name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Publish .NET Project
      run: dotnet publish portfolio.csproj -c Release -o release --nologo

    - name: Add .nojekyll file
      run: touch release/wwwroot/.nojekyll

    # Change base tag in index.html from / to /topedaramola-2025/
    - name: Change base-tag in index.html
      run: |
        cd release/wwwroot
        sed -i 's/<base href="\/"/<base href="\/topedaramola-2025\/"/g' index.html

    - name: Commit wwwroot to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4.5.0
      with:
        folder: release/wwwroot   # The folder the action should deploy.
        branch: gh-pages          # The branch the action should deploy to.
        clean: true              # Automatically remove deleted files from the deploy branch
        clean-exclude: |
          .nojekyll